export const hotProducts = [
  {
    id: 1,
    img: 'img/carousel-hot-products-photos/1.jpg',
    name: 'Термобілизна для бодибілдерів',
    category: 'Для чоловіків',
    moreAboutCategory: '2 кольори',
    price: 4000,
  },
  {
    id: 2,
    img: 'img/carousel-hot-products-photos/2.jpg',
    name: 'Майка для бодібілдерів',
    category: 'Для жінок',
    moreAboutCategory: '6 кольорів',
    price: 1100,
  },
  {
    id: 3,
    img: 'img/carousel-hot-products-photos/3.jpg',
    name: 'Ланцюжок для бодібілдерів',
    category: 'Аксесуари',
    moreAboutCategory: '30 кг.',
    price: 2000,
  },
  {
    id: 4,
    img: 'img/carousel-hot-products-photos/1.jpg',
    name: 'Термобілизна для бодибілдерів',
    category: 'Для чоловіків',
    moreAboutCategory: '2 кольори',
    price: 4000,
  },
  {
    id: 5,
    img: 'img/carousel-hot-products-photos/2.jpg',
    name: 'Майка для бодібілдерів',
    category: 'Для жінок',
    moreAboutCategory: '6 кольорів',
    price: 1100,
  },
  {
    id: 6,
    img: 'img/carousel-hot-products-photos/3.jpg',
    name: 'Ланцюжок для бодібілдерів',
    category: 'Аксесуари',
    moreAboutCategory: '30 кг.',
    price: 2000,
  },
  {
    id: 7,
    img: 'img/carousel-hot-products-photos/1.jpg',
    name: 'Термобілизна для бодибілдерів',
    category: 'Для чоловіків',
    moreAboutCategory: '2 кольори',
    price: 4000,
  },
  {
    id: 8,
    img: 'img/carousel-hot-products-photos/2.jpg',
    name: 'Майка для бодібілдерів',
    category: 'Для жінок',
    moreAboutCategory: '6 кольорів',
    price: 1100,
  },
  {
    id: 9,
    img: 'img/carousel-hot-products-photos/3.jpg',
    name: 'Ланцюжок для бодібілдерів',
    category: 'Аксесуари',
    moreAboutCategory: '30 кг.',
    price: 2000,
  },
  {
    id: 10,
    img: 'img/carousel-hot-products-photos/1.jpg',
    name: 'Термобілизна для бодибілдерів',
    category: 'Для чоловіків',
    moreAboutCategory: '2 кольори',
    price: 4000,
  },
  {
    id: 11,
    img: 'img/carousel-hot-products-photos/2.jpg',
    name: 'Майка для бодібілдерів',
    category: 'Для жінок',
    moreAboutCategory: '6 кольорів',
    price: 1100,
  },
  {
    id: 12,
    img: 'img/carousel-hot-products-photos/3.jpg',
    name: 'Ланцюжок для бодібілдерів',
    category: 'Аксесуари',
    moreAboutCategory: '30 кг.',
    price: 2000,
  }
];

export const comments = [
  {
    id: 1,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 2,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 3,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 4,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 5,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 6,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 7,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 8,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 9,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 10,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 11,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
  {
    id: 12,
    img: 'img/comment-avatar.jpg',
    name: 'Жора Ремінгтон',
    comment: 'Дуже задоволений якістю обслуговування і самою продукцією. Купували термобілизну у подарунок, друзі...',
  },
];
